### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by doublejtoh** [kairos03/kairos-smi#3]
For better server maintenance,  we request some reasonable features.
1. Broadcast Wall message throughout multiple servers
- If one server wall messages, the message is transported to all the other multiple servers.
2. Personal info (name, location, etc) attached to IP address
ex) type command "ksmi-who" prints 
| logged in username | logged in date | IP address | name

**Comment by kairos03** [comment]
Thankyou for feature request after some UI upgrade, I'll add new feature that you suggested.

**Comment by kairos03** [comment]
related #20 #21
